name: Lint Dockerfile

on:
  pull_request:
  push:
  workflow_dispatch:  # Permet un déclenchement manuel

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Utiliser la version v2

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/default  # Règles par défaut de Semgrep

  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2  # Utiliser la version v2

      - name: Run Hadolint
        run: |
          cat Dockerfile | docker run --rm -i hadolint/hadolint:v2.10.0 \
          hadolint --ignore DL3020 --ignore DL3006 -

  super-linter:
    if: github.event_name == 'pull_request'  # Exécuté uniquement sur les PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Utiliser la version v2

      - name: Run Super-Linter
        uses: github/super-linter@v4