name: Lint Workflow

on:
  pull_request:
  push:
  workflow_dispatch:  # Permet un déclenchement manuel

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/default  # Règles par défaut de Semgrep

  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3
        with:
          dockerfile: Dockerfile  # Chemin vers ton Dockerfile

  super-linter:
    if: github.event_name == 'pull_request'  # Exécuté uniquement sur les PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Super-Linter
        uses: github/super-linter@v4