name: Lint Dockerfile

on:
  pull_request:
  push:
  workflow_dispatch:  # Permet un déclenchement manuel

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/default  # Règles par défaut de Semgrep

  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Utiliser la version v3 pour plus de cohérence

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.0.0  # Utiliser la version la plus récente disponible
        with:
          dockerfile: Dockerfile  # Chemin vers ton Dockerfile
          recursive: false
          no-color: false
          no-fail: false
          verbose: false
          format: tty
          failure-threshold: info

  super-linter:
    if: github.event_name == 'pull_request'  # Exécuté uniquement sur les PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Super-Linter
        uses: github/super-linter@v4
